const SERVICES = {
  AUTH: 'auth',
};

const CODES = {
  NOT_FOUND: 'NOT_FOUND',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  FORBIDDEN: 'FORBIDDEN',
  USER_EXISTS: 'USER_EXISTS',
  USER_EXISTS_PHONE: 'USER_EXISTS_PHONE',
  NO_TOKEN: 'NO_TOKEN',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
};

module.exports = { SERVICES, CODES };
